language: objective-c
osx_image: xcode9

before_script:
  - gem install xcpretty

env:
  global:
  - PROJECT=AvatarImageView
  - SCHEME=$PROJECT
  matrix:
    - DESTINATION="name=iPhone 7"
    - DESTINATION="name=iPhone 7 plus"

script: 
  - xcodebuild -project "$PROJECT.xcodeproj" -scheme "$PROJECT" -sdk iphonesimulator -destination "$DESTINATION" test | xcpretty && exit ${PIPESTATUS[0]}

branches:
  only:
  - master
  - develop